routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dev', 'Dev\RouteController@index')->name('dev');
Route::get('/dev/filter', 'Dev\RouteController@filter')->name('filter.user-opd');

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/user/logout', 'Auth\LoginController@logout')->name('user.logout');
Route::post('/user/register/', 'Auth\LoginController@register')->name('user.register');
Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin');

    Route::get('/user-manajemen/delete/{user_manajeman}', 'Admin\UserController@destroy')->name('user-manajemen.delete');
    Route::resource('/user-manajemen', 'Admin\UserController');

    Route::get('/daftar-kegiatan/delete/{daftar_kegiatan}', 'Admin\KegiatanController@destroy')->name('daftar-kegiatan.delete');
    Route::get('/daftar-kegiatan/show-by-date/', 'Admin\KegiatanController@showByDate')->name('daftar-kegiatan.show-by-date');
    Route::get('/daftar-kegiatan/show-by-opd/', 'Admin\KegiatanController@showByOpd')->name('daftar-kegiatan.show-by-opd');
    Route::resource('/daftar-kegiatan', 'Admin\KegiatanController');

    Route::get('/opd-manajemen/delete/{opd_manajemen}', 'Admin\OpdController@destroy')->name('opd-manajemen.delete');
    Route::resource('/opd-manajemen', 'Admin\OpdController');
});

Route::group(['prefix' => 'opd', 'middleware' => ['auth', 'opd']], function () {
    Route::get('/', 'Opd\OpdController@index')->name('opd');
    Route::get('/profile/{id}', 'Opd\OpdController@profile')->name('opd.profile');
    Route::get('/profile/update/{id}/edit', 'Opd\OpdController@editProfile')->name('opd.edit-profile');
    Route::match(['put','patch'],'/profile/update/{id}', 'Opd\OpdController@updateProfile')->name('opd.update-profile');

    Route::get('/kegiatan/delete/{kegiatan}', 'Opd\KegiatanController@destroy')->name('kegiatan.delete');
    Route::get('/kegiatan/show-by-date/', 'Opd\KegiatanController@showByDate')->name('kegiatan.show-by-date');
    Route::resource('/kegiatan', 'Opd\KegiatanController');
});

app/Opd.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Opd extends Model
{
    protected $guarded = [];

    public function kegiatan()
    {
        return $this->hasMany(Kegiatan::class);
    }

    public function user(){
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/Admin/OpdController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Opd;
use Carbon\Carbon;
use File;
use Image;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OpdController extends Controller
{

    public $path;

    public function __construct()
    {
        $this->path = storage_path('app/public/photo-pic');
    }

    public function index()
    {
        $opds = Opd::with('user', 'kegiatan')->orderBy('nama', 'asc')->get();
        return view('pages.admin.opd.opd', compact('opds'));
//        return dd($opds);
    }

    public function create()
    {
        return view('pages.admin.opd.tambahOpd');
    }

    public function store(Request $request)
    {
//        if ($request->hasFile('image')) {
//
//            if (!File::isDirectory($this->path)) {
//                File::makeDirectory($this->path);
//            }
//            $file = $request->file('image');
//            $fileName = Carbon::now()->timestamp . '_' . uniqid() . '.' . $file->getClientOriginalExtension();
//            Image::make($file)->save($this->path . '/' . $fileName);

            $opd = Opd::create([
                'nama' => $request->nama,
                'email' => $request->email,
                'alamat' => $request->alamat,
                'facebook' => $request->facebook,
                'instagram' => $request->instagram,
                'twitter' => $request->twitter,
                'telegram' => $request->telegram,
                'hp_instansi' => $request->hp_instansi,
                'hp_pic' => $request->hp_pic,
//                'foto_pic' => 'photo-pic/'. $fileName,
            ]);
            if ($opd) {
                return redirect()->back()->with(['success' => 'Data OPD berhasil disimpan']);
            } else {
                return redirect()->back()->with(['error' => 'Data OPD gagal disimpan']);
            }
//        }

    }

    public function show($id)
    {

    }

    public function edit($id)
    {
        $opd = Opd::find($id);
        return view('pages.admin.opd.tambahOpd', compact('opd'));
    }

    public function update(Request $request, $id)
    {
        if ($request->hasFile('image')) {

            if (!File::isDirectory($this->path)) {
                File::makeDirectory($this->path);
            }
            $file = $request->file('image');
            $fileName = Carbon::now()->timestamp . '_' . uniqid() . '.' . $file->getClientOriginalExtension();
            Image::make($file)->save($this->path . '/' . $fileName);

            $opd = Opd::find($id);
            $opd = $opd->update([
                'nama' => $request->nama,
                'email' => $request->email,
                'alamat' => $request->alamat,
                'facebook' => $request->facebook,
                'instagram' => $request->instagram,
                'twitter' => $request->twitter,
                'telegram' => $request->telegram,
                'hp_instansi' => $request->hp_instansi,
                'hp_pic' => $request->hp_pic,
                'foto_pic' => 'photo-pic/'.$fileName,
            ]);
            if ($opd) {
                return redirect()->route('opd-manajemen.index')->with(['success' => 'Data OPD berhasil diubah']);
            } else {
                return redirect()->back()->with(['error' => 'Data OPD gagal diubah']);
            }
        } else {
            $opd = Opd::find($id);
            $opd = $opd->update([
                'nama' => $request->nama,
                'email' => $request->email,
                'alamat' => $request->alamat,
                'facebook' => $request->facebook,
                'instagram' => $request->instagram,
                'twitter' => $request->twitter,
                'telegram' => $request->telegram,
                'hp_instansi' => $request->hp_instansi,
                'hp_pic' => $request->hp_pic,
            ]);
            if ($opd) {
                return redirect()->route('opd-manajemen.index')->with(['success' => 'Data OPD berhasil diubah']);
            } else {
                return redirect()->back()->with(['error' => 'Data OPD gagal diubah']);
            }
        }
    }

    public function destroy($id)
    {
        $opd = Opd::findOrFail($id);
        $opd = $opd->delete();
        if ($opd){
            return redirect()->back()->with(['success' => 'Data OPD berhasil dihapus']);
        }else{
            return redirect()->back()->with(['error' => 'Data OPD gagal dihapus']);
        }
    }
}

app/Http/Controllers/Opd/KegiatanController.php
<?php

namespace App\Http\Controllers\Opd;

use App\Kegiatan;
use App\Photo;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Image;
use File;

class KegiatanController extends Controller
{
    public function index()
    {
        $res = Kegiatan::with('photo')
            ->where('opd_id', '=', Auth::user()->opd->id)
            ->orderBy('tanggal_kegiatan', 'desc')
            ->groupBy('tanggal_kegiatan')->paginate(5);
        $kegiatans = array();
        foreach ($res as $keg) {
            array_push($kegiatans, [
                'tanggal' => $keg->tanggal_kegiatan,
                'data' => Kegiatan::where('opd_id', '=', Auth::user()->opd->id)->where('tanggal_kegiatan', '=', $keg->tanggal_kegiatan)->limit(4)->get(),
            ]);
        }
        return view('pages.opd.kegiatan.kegiatan', compact('kegiatans', 'res'));
//        return dd($res);
    }

    public function create()
    {
        return view('pages.opd.kegiatan.formKegiatan');
    }

    public function store(Request $request)
    {

        $path = 'app/public/foto-kegiatan';
        $thumbnail = 'app/public/foto-kegiatan/thumbnail';

        // if ($request->hasFile('foto_kegiatan')) {

        if (!File::isDirectory(storage_path($path))) {
            File::makeDirectory(storage_path($path));
        }

        $file = $request->file('foto_kegiatan');
        $fileName = Carbon::now()->timestamp . '_' . uniqid() . '.' . $file->getClientOriginalExtension();
        Image::make($file)->save(storage_path($path) . '/' . $fileName);

        $canvas = Image::canvas(300, 200);
        $resizeImage = Image::make($file)->fit(300, 200);

        if (!File::isDirectory(storage_path($thumbnail))) {
            File::makeDirectory(storage_path($thumbnail));
        }

        $canvas->insert($resizeImage, 'center');
        $canvas->save(storage_path($thumbnail) . '/' . $fileName);

        $kegiatan = Kegiatan::create([
            'nama_kegiatan' => $request->NamaKegiatan,
            'tanggal_kegiatan' => $request->tanggal,
            'lokasi' => $request->lokasi,
            'narasumber' => $request->narasumber,
            'agenda' => $request->agenda,
            'hasil' => $request->hasil,
            'opd_id' => Auth::user()->opd->id,
        ]);

        if ($kegiatan) {
            $upload = Photo::create([
                'thumbnail' => 'foto-kegiatan/thumbnail/' . $fileName,
                'foto' => 'foto-kegiatan/' . $fileName,
                'kegiatan_id' => $kegiatan->id,
            ]);
            return redirect()->back()->with(['success' => 'Data kegiatan berhasil disimpan']);
        } else {
            return redirect()->back()->with(['error' => 'Data kegiatan gagal disimpan']);
        }
        // }
    }

    public function show($id)
    {
        $kegiatan = Kegiatan::with('photo')->where('id', '=', $id)->first();
        return view('pages.opd.kegiatan.galleryKegiatan', compact('kegiatan'));
//        return dd($kegiatan);
    }

    public function edit($id)
    {
        $kegiatan = User::find($id);
        return view('pages.opd.kegiatan.formKegiatan', compact('kegiatan'));
    }

    public function update(Request $request, $id)
    {
        $kegiatan = Kegiatan::find($id);
        $data = Kegiatan::update([
            'nama_kegiatan' => $request->NamaKegiatan,
            'tanggal_kegiatan' => $request->TanggalKegiatan,
            'lokasi' => $request->lokasi,
            'narasumber' => $request->narasumber,
            'agenda' => $request->agenda,
            'hasil' => $request->hasil,
            'opd_id' => $request->NamaOpd
        ]);

        if ($data) {
            return redirect()->route('daftar-kegiatan.index')->with('success', 'Data kegiatan berhasil diubah');
        } else {
            return redirect()->back()->with('error', 'Data kegiatan gagal diubah');
        }
    }

    public function destroy($id)
    {
        $kegiatan = Kegiatan::find($id);
        $data = Kegiatan::delete();
        if ($data) {
            return redirect()->back()->with(['success' => 'Data kegiatan berhasil dihapus']);
        } else {
            return redirect()->back()->with(['error' => 'Data kegiatan gagal dihapus']);
        }
    }

    public function showByDate(Request $request)
    {
        $kegiatans = Kegiatan::where('opd_id', '=', Auth::user()->opd->id)->where('tanggal_kegiatan', '=', $request->tanggal)->orderBy('tanggal_kegiatan', 'desc')->paginate(8);
        return view('pages.opd.kegiatan.showKegiatanByDate', compact('kegiatans'));
    }
}

app/Http/Controllers/Opd/OpdController.php
<?php

namespace App\Http\Controllers\Opd;

use App\Opd;
use Carbon\Carbon;
use Illuminate\Http\Request;
use File;
use Image;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class OpdController extends Controller
{
    public $path;

    public function __construct()
    {
        $this->path = storage_path('app/public/photo-pic');
    }

    public function index()
    {
//        return view('layout.main');
        return redirect()->route('kegiatan.index');
    }

    public function profile($id){
        $profil = Opd::findOrFail($id);
        return view('pages.opd.profil.profil', compact('profil'));
    }

    public function editProfile($id){
        $opd = Opd::findOrFail($id);
        return view('pages.opd.profil.updateProfile', compact('opd'));
    }

    public function updateProfile(Request $request, $id)
    {
        if ($request->hasFile('image')) {

            if (!File::isDirectory($this->path)) {
                File::makeDirectory($this->path);
            }
            $file = $request->file('image');
            $fileName = Carbon::now()->timestamp . '_' . uniqid() . '.' . $file->getClientOriginalExtension();
            Image::make($file)->save($this->path . '/' . $fileName);

            $opd = Opd::find($id);
            $opd = $opd->update([
                'nama' => $request->nama,
                'email' => $request->email,
                'alamat' => $request->alamat,
                'facebook' => $request->facebook,
                'instagram' => $request->instagram,
                'twitter' => $request->twitter,
                'telegram' => $request->telegram,
                'hp_instansi' => $request->hp_instansi,
                'hp_pic' => $request->hp_pic,
                'foto_pic' => 'photo-pic/'.$fileName,
            ]);
            if ($opd) {
                return redirect()->route('opd.profile', Auth::user()->opd->id)->with(['success' => 'Data OPD berhasil diubah']);
            } else {
                return redirect()->back()->with(['error' => 'Data OPD gagal diubah']);
            }
        } else {
            $opd = Opd::find($id);
            $opd = $opd->update([
                'nama' => $request->nama,
                'email' => $request->email,
                'alamat' => $request->alamat,
                'facebook' => $request->facebook,
                'instagram' => $request->instagram,
                'twitter' => $request->twitter,
                'telegram' => $request->telegram,
                'hp_instansi' => $request->hp_instansi,
                'hp_pic' => $request->hp_pic,
            ]);
            if ($opd) {
                return redirect()->route('opd.profile', Auth::user()->opd->id)->with(['success' => 'Data OPD berhasil diubah']);
            } else {
                return redirect()->back()->with(['error' => 'Data OPD gagal diubah']);
            }
        }
    }

}

resources/views/pages/admin/opd/opd.blade.php
@extends('layout.main')
@section('title','Data Users')
@section('content')
    <section class="content-header">
        <h1>
            OPD Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">OPD Management</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Data OPD Provinsi NTB</h3>
                        <div class="box-tools">
                            <a href="{{route('opd-manajemen.create')}}" class="btn btn-primary btn-sm"><span
                                        class="fa fa-plus"></span> Tambah Data</a>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                @include('layout.includes.notofication')
                            </div>
                            <div class="col-lg-12">
                                <table id="table_id" class="table table-responsive table-hover">
                                    <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama OPD</th>
                                        <th>Enail</th>
                                        <th>Telepon Instansi</th>
                                        <th>Telp./HP PIC</th>
                                        <th>Jumlah User</th>
                                        <th style="">Jumlah Kegiatan</th>
                                        <th>Aksi</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($opds as $opd)
                                        <tr>
                                            <th scope="row">{{$loop->iteration}}</th>
                                            <td>{{$opd->nama}}</td>
                                            <td>{{$opd->email}}</td>
                                            <td>{{$opd->hp_instansi}}</td>
                                            <td>{{$opd->hp_pic}}</td>
                                            <td>
                                                <small class="label bg-primary">{{count($opd->user)}}</small>
                                            </td>
                                            <td>
                                                <small class="label bg-primary">{{count($opd->kegiatan).' '}}</small>
                                                <span>
                                                    <form action="{{route('daftar-kegiatan.show-by-opd')}}" method="GET" style="z-index: auto;margin-top: -25px;margin-left: 10px;">
                                                        @csrf
                                                        <input type="hidden" name="opd" value="{{$opd->id}}">
                                                        <button type="submit" class="btn btn-link">Lihat</button>
                                                    </form>
                                                </span>
                                            </td>
                                            <td style="width: 50px">
                                                {{--<a class="btn btn-primary btn-sm"--}}
                                                {{--href="{{route('opd-manajemen.edit', $opd->id)}}"><i--}}
                                                {{--class="fa fa-eye" title="Detail Kegiatan"></i></a>--}}
                                                <a class="btn btn-primary btn-xs"
                                                   href="{{route('opd-manajemen.edit', $opd->id)}}"><i
                                                            class="fa fa-edit" title="Edit Data"></i></a>
                                                <a class="btn btn-danger btn-xs"
                                                   href="{{route('opd-manajemen.delete', $opd->id)}}"
                                                   onclick="alert('Yakin ingin menghapus data?')"><i
                                                            class="fa fa-trash" title="Hapus Data"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

resources/views/pages/admin/opd/tambahOpd.blade.php
@extends('layout.main')
@section('title','Tambah Data Users')
@section('content')
    <section class="content-header">
        <h1>
            OPD Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-user"></i> Home</a></li>
            <li class="active">Tambah OPD</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                @include('layout.includes.notofication')
            </div>
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-body">
                        @if(isset($opd))
                            <form action="{{route('opd-manajemen.update', $opd->id)}}" method="POST" enctype="multipart/form-data">
                                {{csrf_field()}}
                                {{method_field('PUT')}}
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Nama OPD <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" placeholder="Nama OPD" name="nama"
                                                   value="{{$opd->nama}}" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Email <span class="text-danger">*</span></label>
                                            <input type="email" class="form-control" name="email"
                                                   placeholder="Email OPD" value="{{$opd->email}}" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Facebook</label>
                                            <input type="text" class="form-control" name="facebook"
                                                   placeholder="Facebook OPD" value="{{$opd->facebook}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Instagram</label>
                                            <input type="text" class="form-control" name="instagram"
                                                   placeholder="Instagram OPD" value="{{$opd->instagram}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Twitter</label>
                                            <input type="text" class="form-control" name="twitter"
                                                   placeholder="Twitter OPD" {{$opd->twitter}}>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Telegram</label>
                                            <input type="text" class="form-control" name="telegram"
                                                   placeholder="Telegram OPD" {{$opd->telegram}}>
                                        </div>
                                        <div class="form-group">
                                            <label>Telepon/HP OPD <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" name="hp_instansi"
                                                   placeholder="Nomor Telepon OPD" value="{{$opd->hp_instansi}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Alamat OPD <span class="text-danger">*</span></label>
                                            <textarea class="form-control" name="alamat" id=""
                                                      placeholder="Alamat OPD">{{$opd->alamat}}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Telepon/HP PIC <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" name="hp_pic"
                                                   placeholder="Nomor Telepon PIC" value="{{$opd->hp_pic}}">
                                        </div>
                                        {{-- <div class="form-group">
                                            <label>Foto PIC <span class="text-danger">*</span></label>
                                            <input type="file" name="image" id="image" class="form-control">
                                            <p class="text-muted">Kosongkan jika tidak ingin mengubah foto</p>
                                        </div> --}}
                                    </div>
                                </div>
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Simpan</button>
                                    <button type="reset" class="btn btn-danger">Reset</button>
                                </div>
                            </form>
                        @else
                            <form action="{{route('opd-manajemen.store')}}" method="POST" enctype="multipart/form-data">
                                {{csrf_field()}}
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Nama OPD <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" placeholder="Nama OPD" name="nama"
                                                   required autofocus>
                                        </div>
                                        <div class="form-group">
                                            <label>Email <span class="text-danger">*</span></label>
                                            <input type="email" class="form-control" name="email"
                                                   placeholder="Email OPD" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Facebook</label>
                                            <input type="text" class="form-control" name="facebook"
                                                   placeholder="Facebook OPD">
                                        </div>
                                        <div class="form-group">
                                            <label>Instagram</label>
                                            <input type="text" class="form-control" name="instagram"
                                                   placeholder="Instagram OPD">
                                        </div>
                                        <div class="form-group">
                                            <label>Twitter</label>
                                            <input type="text" class="form-control" name="twitter"
                                                   placeholder="Twitter OPD">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Telegram</label>
                                            <input type="text" class="form-control" name="telegram"
                                                   placeholder="Telegram OPD">
                                        </div>
                                        <div class="form-group">
                                            <label>Telepon/HP OPD <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" name="hp_instansi"
                                                   placeholder="Nomor Telepon OPD">
                                        </div>
                                        <div class="form-group">
                                            <label>Alamat OPD <span class="text-danger">*</span></label>
                                            <textarea class="form-control" name="alamat" id=""
                                                      placeholder="Alamat OPD"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Telepon/HP PIC <span class="text-danger">*</span></label>
                                            <input type="text" class="form-control" name="hp_pic"
                                                   placeholder="Nomor Telepon PIC">
                                        </div>
                                        {{-- <div class="form-group">
                                            <label>Foto PIC <span class="text-danger">*</span></label>
                                            <input type="file" name="image" id="image" class="form-control" required>
                                        </div> --}}
                                    </div>
                                </div>
                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Simpan</button>
                                    <button type="reset" class="btn btn-danger">Reset</button>
                                </div>
                            </form>
                        @endIf
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop