routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dev', 'Dev\RouteController@index')->name('dev');
Route::get('/dev/filter', 'Dev\RouteController@filter')->name('filter.user-opd');

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/user/logout', 'Auth\LoginController@logout')->name('user.logout');
Route::post('/user/register/', 'Auth\LoginController@register')->name('user.register');
Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin');

    Route::get('/user-manajemen/delete/{user_manajeman}', 'Admin\UserController@destroy')->name('user-manajemen.delete');
    Route::resource('/user-manajemen', 'Admin\UserController');

    Route::get('/daftar-kegiatan/delete/{daftar_kegiatan}', 'Admin\KegiatanController@destroy')->name('daftar-kegiatan.delete');
    Route::get('/daftar-kegiatan/show-by-date/', 'Admin\KegiatanController@showByDate')->name('daftar-kegiatan.show-by-date');
    Route::get('/daftar-kegiatan/show-by-opd/', 'Admin\KegiatanController@showByOpd')->name('daftar-kegiatan.show-by-opd');
    Route::resource('/daftar-kegiatan', 'Admin\KegiatanController');

    Route::get('/opd-manajemen/delete/{opd_manajemen}', 'Admin\OpdController@destroy')->name('opd-manajemen.delete');
    Route::resource('/opd-manajemen', 'Admin\OpdController');
});

Route::group(['prefix' => 'opd', 'middleware' => ['auth', 'opd']], function () {
    Route::get('/', 'Opd\OpdController@index')->name('opd');
    Route::get('/profile/{id}', 'Opd\OpdController@profile')->name('opd.profile');
    Route::get('/profile/update/{id}/edit', 'Opd\OpdController@editProfile')->name('opd.edit-profile');
    Route::match(['put','patch'],'/profile/update/{id}', 'Opd\OpdController@updateProfile')->name('opd.update-profile');

    Route::get('/kegiatan/delete/{kegiatan}', 'Opd\KegiatanController@destroy')->name('kegiatan.delete');
    Route::get('/kegiatan/show-by-date/', 'Opd\KegiatanController@showByDate')->name('kegiatan.show-by-date');
    Route::resource('/kegiatan', 'Opd\KegiatanController');
});

app/Http/Controllers/Admin/KegiatanController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Kegiatan;

class KegiatanController extends Controller
{
    public function index()
    {
        $res = Kegiatan::with('photo')
            ->orderBy('tanggal_kegiatan', 'desc')
            ->groupBy('tanggal_kegiatan')->paginate(5);
        $kegiatans = array();
        foreach ($res as $keg) {
            array_push($kegiatans, [
                'tanggal' => $keg->tanggal_kegiatan,
                'data' => Kegiatan::with('opd')->where('tanggal_kegiatan', '=', $keg->tanggal_kegiatan)->limit(4)->get(),
            ]);
        }
        return view('pages.admin.kegiatan.kegiatan', compact('kegiatans','res'));
//        return dd($kegiatans);
    }

    public function create()
    {
        $opds = Opd::orderBy('nama', 'asc')->get();
        return view('pages.admin.kegiatan.tambahKegiatan', compact('opds'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nama_kegiatan' => 'required',
            'tanggal_kegiatan' => 'required',
            'lokasi' => 'required',
            'narasumber' => 'required',
            'agenda' => 'required',
            'hasil' => 'required',
        ]);

        if ($validatedData) {
            if ($request->has('opd_id')) {
                $data = Kegiatan::create([
                    'nama_kegiatan' => $request->nama_kegiatan,
                    'tanggal_kegiatan' => $request->tanggal_kegiatan,
                    'lokasi' => $request->lokasi,
                    'narasumber' => $request->narasumber,
                    'agenda' => $request->agenda,
                    'hasil' => $request->hasil,
                    'opd_id' => $request->opd_id
                ]);

                if ($data) {
                    return redirect()->back()->with(['status' => true, 'message' => 'Success']);
                }
            } else {
                $data = Kegiatan::create([
                    'nama_kegiatan' => $request->nama_kegiatan,
                    'tanggal_kegiatan' => $request->tanggal_kegiatan,
                    'lokasi' => $request->lokasi,
                    'narasumber' => $request->narasumber,
                    'agenda' => $request->agenda,
                    'hasil' => $request->hasil,
                ]);

                if ($data) {
                    return redirect()->back()->with(['status' => true, 'message' => 'Success']);
                }
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kegiatan = Kegiatan::with('photo')->where('id', '=', $id)->first();
        return view('pages.admin.kegiatan.galleryKegiatan', compact('kegiatan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Kegiatan $kegiatan)
    {
        return dd($kegiatan);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kegiatan $kegiatan)
    {
        $validatedData = $request->validate([
            'nama_kegiatan' => 'required',
            'tanggal_kegiatan' => 'required',
            'lokasi' => 'required',
            'narasumber' => 'required',
            'agenda' => 'required',
            'hasil' => 'required',
        ]);

        if ($validatedData) {
            if ($request->has('opd_id')) {
                $data = Kegiatan::update([
                    'nama_kegiatan' => $request->nama_kegiatan,
                    'tanggal_kegiatan' => $request->tanggal_kegiatan,
                    'lokasi' => $request->lokasi,
                    'narasumber' => $request->narasumber,
                    'agenda' => $request->agenda,
                    'hasil' => $request->hasil,
                    'opd_id' => $request->opd_id
                ]);

                if ($data) {
                    return redirect()->back()->with(['status' => true, 'message' => 'Updated']);
                }
            } else {
                $data = Kegiatan::create([
                    'nama_kegiatan' => $request->nama_kegiatan,
                    'tanggal_kegiatan' => $request->tanggal_kegiatan,
                    'lokasi' => $request->lokasi,
                    'narasumber' => $request->narasumber,
                    'agenda' => $request->agenda,
                    'hasil' => $request->hasil,
                ]);

                if ($data) {
                    return redirect()->back()->with(['status' => true, 'message' => 'Updated']);
                }
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kegiatan $kegiatan)
    {
        $kegiatan->delete();
        return redirect()->back()->with(['status' => true, 'message' => 'Deleted']);
    }

    public function showByDate(Request $request)
    {
        $kegiatans = Kegiatan::with('opd')->where('tanggal_kegiatan', '=', $request->tanggal)->orderBy('tanggal_kegiatan', 'desc')->paginate(8);
        return view('pages.admin.kegiatan.showKegiatanByDate', compact('kegiatans'));
//        return dd($kegiatans);
    }

    public function showByOpd(Request $request)
    {
        $kegiatans = Kegiatan::with('opd')->where('opd_id', '=', $request->opd)->orderBy('tanggal_kegiatan', 'desc')->paginate(8);
        return view('pages.admin.kegiatan.showKegiatanByOpd', compact('kegiatans'));
//        return dd($kegiatans);
    }
}

app/Http/Controllers/Admin/OpdController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Opd;
use Carbon\Carbon;
use File;
use Image;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OpdController extends Controller
{

    public $path;

    public function __construct()
    {
        $this->path = storage_path('app/public/photo-pic');
    }

    public function index()
    {
        $opds = Opd::with('user', 'kegiatan')->orderBy('nama', 'asc')->get();
        return view('pages.admin.opd.opd', compact('opds'));
//        return dd($opds);
    }

    public function create()
    {
        return view('pages.admin.opd.tambahOpd');
    }

    public function store(Request $request)
    {
//        if ($request->hasFile('image')) {
//
//            if (!File::isDirectory($this->path)) {
//                File::makeDirectory($this->path);
//            }
//            $file = $request->file('image');
//            $fileName = Carbon::now()->timestamp . '_' . uniqid() . '.' . $file->getClientOriginalExtension();
//            Image::make($file)->save($this->path . '/' . $fileName);

            $opd = Opd::create([
                'nama' => $request->nama,
                'email' => $request->email,
                'alamat' => $request->alamat,
                'facebook' => $request->facebook,
                'instagram' => $request->instagram,
                'twitter' => $request->twitter,
                'telegram' => $request->telegram,
                'hp_instansi' => $request->hp_instansi,
                'hp_pic' => $request->hp_pic,
//                'foto_pic' => 'photo-pic/'. $fileName,
            ]);
            if ($opd) {
                return redirect()->back()->with(['success' => 'Data OPD berhasil disimpan']);
            } else {
                return redirect()->back()->with(['error' => 'Data OPD gagal disimpan']);
            }
//        }

    }

    public function show($id)
    {

    }

    public function edit($id)
    {
        $opd = Opd::find($id);
        return view('pages.admin.opd.tambahOpd', compact('opd'));
    }

    public function update(Request $request, $id)
    {
        if ($request->hasFile('image')) {

            if (!File::isDirectory($this->path)) {
                File::makeDirectory($this->path);
            }
            $file = $request->file('image');
            $fileName = Carbon::now()->timestamp . '_' . uniqid() . '.' . $file->getClientOriginalExtension();
            Image::make($file)->save($this->path . '/' . $fileName);

            $opd = Opd::find($id);
            $opd = $opd->update([
                'nama' => $request->nama,
                'email' => $request->email,
                'alamat' => $request->alamat,
                'facebook' => $request->facebook,
                'instagram' => $request->instagram,
                'twitter' => $request->twitter,
                'telegram' => $request->telegram,
                'hp_instansi' => $request->hp_instansi,
                'hp_pic' => $request->hp_pic,
                'foto_pic' => 'photo-pic/'.$fileName,
            ]);
            if ($opd) {
                return redirect()->route('opd-manajemen.index')->with(['success' => 'Data OPD berhasil diubah']);
            } else {
                return redirect()->back()->with(['error' => 'Data OPD gagal diubah']);
            }
        } else {
            $opd = Opd::find($id);
            $opd = $opd->update([
                'nama' => $request->nama,
                'email' => $request->email,
                'alamat' => $request->alamat,
                'facebook' => $request->facebook,
                'instagram' => $request->instagram,
                'twitter' => $request->twitter,
                'telegram' => $request->telegram,
                'hp_instansi' => $request->hp_instansi,
                'hp_pic' => $request->hp_pic,
            ]);
            if ($opd) {
                return redirect()->route('opd-manajemen.index')->with(['success' => 'Data OPD berhasil diubah']);
            } else {
                return redirect()->back()->with(['error' => 'Data OPD gagal diubah']);
            }
        }
    }

    public function destroy($id)
    {
        $opd = Opd::findOrFail($id);
        $opd = $opd->delete();
        if ($opd){
            return redirect()->back()->with(['success' => 'Data OPD berhasil dihapus']);
        }else{
            return redirect()->back()->with(['error' => 'Data OPD gagal dihapus']);
        }
    }
}

app/Http/Controllers/Opd/KegiatanController.php
<?php

namespace App\Http\Controllers\Opd;

use App\Kegiatan;
use App\Photo;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Image;
use File;

class KegiatanController extends Controller
{
    public function index()
    {
        $res = Kegiatan::with('photo')
            ->where('opd_id', '=', Auth::user()->opd->id)
            ->orderBy('tanggal_kegiatan', 'desc')
            ->groupBy('tanggal_kegiatan')->paginate(5);
        $kegiatans = array();
        foreach ($res as $keg) {
            array_push($kegiatans, [
                'tanggal' => $keg->tanggal_kegiatan,
                'data' => Kegiatan::where('opd_id', '=', Auth::user()->opd->id)->where('tanggal_kegiatan', '=', $keg->tanggal_kegiatan)->limit(4)->get(),
            ]);
        }
        return view('pages.opd.kegiatan.kegiatan', compact('kegiatans', 'res'));
//        return dd($res);
    }

    public function create()
    {
        return view('pages.opd.kegiatan.formKegiatan');
    }

    public function store(Request $request)
    {

        $path = 'app/public/foto-kegiatan';
        $thumbnail = 'app/public/foto-kegiatan/thumbnail';

        // if ($request->hasFile('foto_kegiatan')) {

        if (!File::isDirectory(storage_path($path))) {
            File::makeDirectory(storage_path($path));
        }

        $file = $request->file('foto_kegiatan');
        $fileName = Carbon::now()->timestamp . '_' . uniqid() . '.' . $file->getClientOriginalExtension();
        Image::make($file)->save(storage_path($path) . '/' . $fileName);

        $canvas = Image::canvas(300, 200);
        $resizeImage = Image::make($file)->fit(300, 200);

        if (!File::isDirectory(storage_path($thumbnail))) {
            File::makeDirectory(storage_path($thumbnail));
        }

        $canvas->insert($resizeImage, 'center');
        $canvas->save(storage_path($thumbnail) . '/' . $fileName);

        $kegiatan = Kegiatan::create([
            'nama_kegiatan' => $request->NamaKegiatan,
            'tanggal_kegiatan' => $request->tanggal,
            'lokasi' => $request->lokasi,
            'narasumber' => $request->narasumber,
            'agenda' => $request->agenda,
            'hasil' => $request->hasil,
            'opd_id' => Auth::user()->opd->id,
        ]);

        if ($kegiatan) {
            $upload = Photo::create([
                'thumbnail' => 'foto-kegiatan/thumbnail/' . $fileName,
                'foto' => 'foto-kegiatan/' . $fileName,
                'kegiatan_id' => $kegiatan->id,
            ]);
            return redirect()->back()->with(['success' => 'Data kegiatan berhasil disimpan']);
        } else {
            return redirect()->back()->with(['error' => 'Data kegiatan gagal disimpan']);
        }
        // }
    }

    public function show($id)
    {
        $kegiatan = Kegiatan::with('photo')->where('id', '=', $id)->first();
        return view('pages.opd.kegiatan.galleryKegiatan', compact('kegiatan'));
//        return dd($kegiatan);
    }

    public function edit($id)
    {
        $kegiatan = User::find($id);
        return view('pages.opd.kegiatan.formKegiatan', compact('kegiatan'));
    }

    public function update(Request $request, $id)
    {
        $kegiatan = Kegiatan::find($id);
        $data = Kegiatan::update([
            'nama_kegiatan' => $request->NamaKegiatan,
            'tanggal_kegiatan' => $request->TanggalKegiatan,
            'lokasi' => $request->lokasi,
            'narasumber' => $request->narasumber,
            'agenda' => $request->agenda,
            'hasil' => $request->hasil,
            'opd_id' => $request->NamaOpd
        ]);

        if ($data) {
            return redirect()->route('daftar-kegiatan.index')->with('success', 'Data kegiatan berhasil diubah');
        } else {
            return redirect()->back()->with('error', 'Data kegiatan gagal diubah');
        }
    }

    public function destroy($id)
    {
        $kegiatan = Kegiatan::find($id);
        $data = Kegiatan::delete();
        if ($data) {
            return redirect()->back()->with(['success' => 'Data kegiatan berhasil dihapus']);
        } else {
            return redirect()->back()->with(['error' => 'Data kegiatan gagal dihapus']);
        }
    }

    public function showByDate(Request $request)
    {
        $kegiatans = Kegiatan::where('opd_id', '=', Auth::user()->opd->id)->where('tanggal_kegiatan', '=', $request->tanggal)->orderBy('tanggal_kegiatan', 'desc')->paginate(8);
        return view('pages.opd.kegiatan.showKegiatanByDate', compact('kegiatans'));
    }
}

resources/views/pages/opd/kegiatan/formKegiatan.blade.php
@extends('layout.main')
@section('title','Tambah Data Kegiatan')
@section('content')
    <section class="content-header">
        <h1>
            User Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-user"></i> Home</a></li>
            <li class="active">Tambah Kegiatan</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                @include('layout.includes.notofication')
            </div>
            <div class="col-md-8 col-md-offset-2">
                <div class="box box-primary">
                    <form action="{{ route('kegiatan.store') }}" method="POST" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="box-body">
                            <div class="form-group">
                                <label>Nama Kegiatan <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="NamaKegiatan" required>
                            </div>
                            <div class="form-group">
                                <label>Tanggal Kegiatan <span class="text-danger">*</span></label>
                                <div class="input-group date" style="width: 100% !important;">
                                    <input type="text" class="form-control" name="tanggal" id="datepicker"
                                           style="width: 100% !important;" autocomplete="false" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Lokasi <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="lokasi" required>
                            </div>
                            <div class="form-group">
                                <label>Narasumber <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="narasumber" required>
                            </div>
                            <div class="form-group">
                                <label>Agenda <span class="text-danger">*</span></label>
                                <textarea class="form-control" name="agenda" id=""placeholder="Agenda" required></textarea>
                            </div>
                            <div class="form-group">
                                <label>Hasil <span class="text-danger">*</span></label>
                                <textarea class="form-control" name="hasil" id="" placeholder="Hasil kegiatan" required></textarea>
                            </div>
                            <div class="form-group">
                                <label>Foto Kegiatan <span class="text-danger">*</span></label>
                                <input type="file" class="form-control" name="foto_kegiatan" required>
                                <sub>Mohon upload gambar berekstensi <b class="text-red">JPG</b>, <b class="text-red">JPEG</b>, <b class="text-red">PNG</b></sub>
                            </div>
                        </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </div>
                </form>
                <div class="col-lg-2"></div>
            </div>
        </div>
    </section>
@stop

resources/views/pages/opd/kegiatan/galleryKegiatan.blade.php
@extends('layout.main')
@section('title','Gallery Kegiatan')
@section('content')
    <section class="content-header">
        <h1>
            Detail Kegiatan
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-user"></i> Home</a></li>
            <li class="active">Kegiatan</li>
            <li class="active">{{$kegiatan->nama_kegiatan}}</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-10">
                <div class="box box-widget">
                    <div class="box-header with-border" style="padding:0 !important;">

                    </div>
                    <div class="box-body">
                        <span class="username">
                            <h3>{{$kegiatan->nama_kegiatan}}</h3>
                        </span>
                        <br>
                        <span class="description"><i class="fa fa-map-pin"></i> {{$kegiatan->lokasi}} - <i
                                    class="fa fa-clock-o"></i> {{$kegiatan->tanggal_kegiatan}}</span>
                        <hr>
                        <h4>Narasumber : <span>{{$kegiatan->narasumber}}</span></h4>
                        <h4>Agenda : </h4>
                        <div class="callout" style="background-color: #EEEEEE">
                            <p>{{$kegiatan->agenda}}</p>
                        </div>
                        <h4>Hasil :</h4>
                        <div class="callout callout-info">
                            <p>{{$kegiatan->hasil}}</p>
                        </div>
                    </div>
                    <div class="box-footer">
                        @foreach($kegiatan->photo as $photo)
                            <a href="{{asset('storage/'.$photo->foto)}}" download="" class="btn btn-primary btn-sm"><i class="fa fa-download"></i> Download Gambar</a>
                        @endforeach
                    </div>
                </div>
            </div>
            <div class="col-lg-1"></div>
        </div>
    </section>
@stop

resources/views/pages/opd/kegiatan/kegiatan.blade.php
@extends('layout.main')
@section('title','Daftar Kegiatan')
@section('content')
    <section class="content-header">
        <h1>
            Data Kegiatan
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Daftar Kegiatan</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Daftar Kegiatan</h3>
                        <div class="box-tools">
                            <a href="{{route('kegiatan.create')}}" class="btn btn-primary btn-sm"><span
                                        class="fa fa-plus"></span> Tambah Kegiatan</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            @foreach($kegiatans as $keg)
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-header bg-info">
                            <h3 class="box-title">Kegiatan pada tanggal : <span
                                        class="text-muted">{{$keg['tanggal']}}</span></h3>
                        </div>
                        <div class="box-body row">
                            @foreach($keg['data'] as $data)
                                <div class="col-md-3">
                                    <div class="box box-solid box-default">
                                        <div class="box-header" style="padding: 0 !important;">
                                            {{--@foreach($keg->photo as $photo)--}}
                                            {{--<img src="{{asset('storage/'.$photo->thumbnail)}}"--}}
                                            {{--alt="" width="100%">--}}
                                            {{--@endforeach--}}
                                        </div>
                                        <div class="box-body">
                                            <div class="title-head"
                                                 style="border-bottom: 1px solid #f4f4f4; padding-bottom: 5px">
                                                @if(strlen($data->nama_kegiatan) >= 30)
                                                    {{substr($data->nama_kegiatan, 0, 30)."..."}}
                                                @else
                                                    {{$data->nama_kegiatan}}
                                                @endif
                                            </div>
                                            <sub class="text-muted"><i class="fa fa-clock-o"></i>
                                                <span>{{$data->tanggal_kegiatan}}</span></sub>
                                            <sub class="text-muted"><i class="fa fa-map-pin"></i>
                                                <span>{{$data->lokasi}}</span></sub>
                                        </div>
                                        <div class="box-footer">
                                            <a href="{{route('kegiatan.show', $data->id)}}"
                                               class="btn btn-block btn-default btn-sm btn-flat"><i class="fa fa-eye"></i> Detail</a>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                            <div class="col-md-12" style="border-top: 1px solid #f4f4f4; padding-bottom: 5px; margin-bottom: -12px">
                                <form action="{{route('kegiatan.show-by-date')}}" method="get">
                                    @csrf
                                    <input type="hidden" name="tanggal" value="{{$keg['tanggal']}}">
                                    <button type="submit" class="btn btn-link pull-right">Lihat semua kegiatan <i class=" fa fa-arrow-right"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
            <div class="text-center">{{$res->links()}}</div>
        </div>
    </section>
@stop

resources/views/pages/opd/kegiatan/showKegiatanByDate.blade.php
@extends('layout.main')
@section('title','Daftar Kegiatan')
@section('content')
    <section class="content-header">
        <h1>
            Data Kegiatan
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Daftar Kegiatan</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Daftar Kegiatan</h3>
                        <div class="box-tools">
                            <a href="{{route('kegiatan.create')}}" class="btn btn-primary btn-sm"><span
                                        class="fa fa-plus"></span> Tambah Kegiatan</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            @foreach($kegiatans as $data)
                <div class="col-md-3">
                    <div class="box box-solid box-default">
                        <div class="box-header" style="padding: 0 !important;">
                            {{--@foreach($keg->photo as $photo)--}}
                                {{--<img src="{{asset('storage/'.$photo->thumbnail)}}"--}}
                                     {{--alt="" width="100%">--}}
                            {{--@endforeach--}}
                        </div>
                        <div class="box-body">
                            <div class="title-head" style="border-bottom: 1px solid #f4f4f4; padding-bottom: 5px">
                                @if(strlen($data->nama_kegiatan) >= 30)
                                    {{substr($data->nama_kegiatan, 0, 30)."..."}}
                                @else
                                    {{$data->nama_kegiatan}}
                                @endif
                            </div>
                            <sub class="text-muted"><i class="fa fa-clock-o"></i>
                                <span>{{$data->tanggal_kegiatan}}</span></sub>
                            <sub class="text-muted"><i class="fa fa-map-pin"></i>
                                <span>{{$data->lokasi}}</span></sub>
                        </div>
                        <div class="box-footer">
                            <a href="{{route('kegiatan.show', $data->id)}}"
                               class="btn btn-block btn-default">Detail</a>
                        </div>
                    </div>
                </div>
            @endforeach
            <div class="text-center">{{$kegiatans->links()}}</div>
        </div>
    </section>
@stop