routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dev', 'Dev\RouteController@index')->name('dev');
Route::get('/dev/filter', 'Dev\RouteController@filter')->name('filter.user-opd');

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/user/logout', 'Auth\LoginController@logout')->name('user.logout');
Route::post('/user/register/', 'Auth\LoginController@register')->name('user.register');
Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin');

    Route::get('/user-manajemen/delete/{user_manajeman}', 'Admin\UserController@destroy')->name('user-manajemen.delete');
    Route::resource('/user-manajemen', 'Admin\UserController');

    Route::get('/daftar-kegiatan/delete/{daftar_kegiatan}', 'Admin\KegiatanController@destroy')->name('daftar-kegiatan.delete');
    Route::get('/daftar-kegiatan/show-by-date/', 'Admin\KegiatanController@showByDate')->name('daftar-kegiatan.show-by-date');
    Route::get('/daftar-kegiatan/show-by-opd/', 'Admin\KegiatanController@showByOpd')->name('daftar-kegiatan.show-by-opd');
    Route::resource('/daftar-kegiatan', 'Admin\KegiatanController');

    Route::get('/opd-manajemen/delete/{opd_manajemen}', 'Admin\OpdController@destroy')->name('opd-manajemen.delete');
    Route::resource('/opd-manajemen', 'Admin\OpdController');
});

Route::group(['prefix' => 'opd', 'middleware' => ['auth', 'opd']], function () {
    Route::get('/', 'Opd\OpdController@index')->name('opd');
    Route::get('/profile/{id}', 'Opd\OpdController@profile')->name('opd.profile');
    Route::get('/profile/update/{id}/edit', 'Opd\OpdController@editProfile')->name('opd.edit-profile');
    Route::match(['put','patch'],'/profile/update/{id}', 'Opd\OpdController@updateProfile')->name('opd.update-profile');

    Route::get('/kegiatan/delete/{kegiatan}', 'Opd\KegiatanController@destroy')->name('kegiatan.delete');
    Route::get('/kegiatan/show-by-date/', 'Opd\KegiatanController@showByDate')->name('kegiatan.show-by-date');
    Route::resource('/kegiatan', 'Opd\KegiatanController');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function opd(){
        return $this->belongsTo(Opd::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Opd;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $managementUser = User::with('opd')->orderBy('nama', 'asc')->where('role', '=', 'user')->get();
        return view('pages.admin.user.user', compact('managementUser'));
//                return dd($managementUser);
    }

    public function create()
    {
        $opds = Opd::orderBy('nama', 'asc')->get();
        return view('pages.admin.user.formUser', compact('opds'));
    }

    public function store(Request $request)
    {
        $data = User::create([
            'nama' => $request->nama,
            'email' => $request->email,
            'username' => $request->username,
            'password' => Hash::make($request->password),
            'role' => 'user',
            'opd_id' => $request->NamaOpd
        ]);

        if ($data) {
            return redirect()->back()->with(['success' => 'Data user berhasil disimpan']);
        } else {
            return redirect()->route('user-manajemen.index')->with(['success' => 'Data user berhasil disimpan']);
        }
    }

    public function show($id)
    {
        return dd($id);
    }

    public function edit($id)
    {
        $opds = Opd::orderBy('nama', 'asc')->get();
        $user = User::find($id);
        return view('pages.admin.user.formUser', compact('user', 'opds'));
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);
        if ($request->has('password')){
            $status = $user->update([
                'nama' => $request->nama,
                'email' => $request->email,
                'username' => $request->username,
                'password' => Hash::make($request->password),
            ]);
        }else{
            $status = $user->update([
                'nama' => $request->nama,
                'email' => $request->email,
                'username' => $request->username,
            ]);
        }


        if ($status) {
            return redirect()->route('user-manajemen.index')->with('success', 'Data user berhasil diubah');
        } else {
            return redirect()->back()->with('error', 'Data user gagal diubah');
        }
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user = $user->delete();
        if ($user) {
            return redirect()->back()->with(['success' => 'Data user berhasil dihapus']);
        } else {
            return redirect()->back()->with(['error' => 'Data user gagal dihapus']);
        }
    }
}

resources/views/pages/admin/user/formUser.blade.php
@extends('layout.main')
@section('title','Form Data Users')
@section('content')
    @if (isset($user))
        <section class="content-header">
            <h1>
                User Management
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-user"></i> Home</a></li>
                <li class="active">Update User</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    @include('layout.includes.notofication')
                </div>
                <div class="col-lg-12">
                    <div class="box box-primary">
                        <form action="{{ route('user-manajemen.update', $user->id) }}" method="POST">
                            <div class="box-body">
                                {{csrf_field()}}
                                {{method_field('PUT')}}
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Organisasi Perangkat Daerah</label>
                                        <select name="NamaOpd" id="" class="form-control select2" required disabled>
                                            <option value="" selected disabled="">Pilih OPD</option>
                                            @foreach($opds as $opd)
                                                <option value="{{$opd->id}}" {{$opd->id == $user->opd->id ? 'selected' : ''}} >{{$opd->nama}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Nama</label>
                                        <input type="text" class="form-control" name="nama" value="{{$user->nama}}" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" class="form-control" name="email" value="{{$user->email}}" required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input type="text" class="form-control" name="username" value="{{$user->username}}" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="password" class="form-control" name="password">
                                        <p class="text-muted">Kosongkan jika tidak ingin mengubah password</p>
                                    </div>
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                                <button type="button" class="btn btn-danger">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    @else
        <section class="content-header">
            <h1>
                User Management
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-user"></i> Home</a></li>
                <li class="active">Tambah User</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    @include('layout.includes.notofication')
                </div>
                <div class="col-lg-12">
                    <div class="box box-primary">
                        <form action="{{ route('user-manajemen.store') }}" method="POST">
                            <div class="box-body">
                                {{csrf_field()}}
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Organisasi Perangkat Daerah</label>
                                        <select name="NamaOpd" id="" class="form-control select2" required>
                                            <option value="" selected disabled="">Pilih OPD</option>
                                            @foreach($opds as $opd)
                                                <option value="{{$opd->id}}">{{$opd->nama}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Nama</label>
                                        <input type="text" class="form-control" name="nama" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" class="form-control" name="email" required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input type="text" class="form-control" name="username" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="password" class="form-control" name="password" required>
                                    </div>
                                </div>
                            </div>
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                                <button type="reset" class="btn btn-danger">Reset</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    @endif
@stop

resources/views/pages/admin/user/user.blade.php
@extends('layout.main')
@section('title','Data Users')
@section('content')
    <section class="content-header">
        <h1>
            User Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">User Management</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                @include('layout.includes.notofication')
            </div>
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Data User OPD Provinsi NTB</h3>
                        <div class="box-tools">
                            <a href="{{route('user-manajemen.create')}}" class="btn btn-primary btn-sm"><span
                                        class="fa fa-plus"></span> Tambah Data</a>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <table id="table_id" class="table table-responsive table-hover">
                                    <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>OPD</th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>Username</th>
                                        <th>Aksi</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($managementUser as $user)
                                        <tr>
                                            <th scope="row">{{$loop->iteration}}</th>
                                            <td>{{$user->opd->nama}}</td>
                                            <td>{{$user->nama}}</td>
                                            <td>{{$user->email}}</td>
                                            <td>{{$user->username}}</td>
                                            <td>
                                                <a href="{{route('user-manajemen.edit', $user->id)}}"
                                                   class="btn btn-primary btn-sm" type="submit" title="Edit Data"><span
                                                            class="fa fa-edit"></span></a>
                                                <a class="btn btn-danger btn-sm"
                                                   href="{{route('user-manajemen.delete', $user->id)}}"
                                                   onclick="alert('Yakin ingin menghapus data?')"><i
                                                            class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop