routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dev', 'Dev\RouteController@index')->name('dev');
Route::get('/dev/filter', 'Dev\RouteController@filter')->name('filter.user-opd');

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/user/logout', 'Auth\LoginController@logout')->name('user.logout');
Route::post('/user/register/', 'Auth\LoginController@register')->name('user.register');
Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'Admin\AdminController@index')->name('admin');

    Route::get('/user-manajemen/delete/{user_manajeman}', 'Admin\UserController@destroy')->name('user-manajemen.delete');
    Route::resource('/user-manajemen', 'Admin\UserController');

    Route::get('/daftar-kegiatan/delete/{daftar_kegiatan}', 'Admin\KegiatanController@destroy')->name('daftar-kegiatan.delete');
    Route::get('/daftar-kegiatan/show-by-date/', 'Admin\KegiatanController@showByDate')->name('daftar-kegiatan.show-by-date');
    Route::get('/daftar-kegiatan/show-by-opd/', 'Admin\KegiatanController@showByOpd')->name('daftar-kegiatan.show-by-opd');
    Route::resource('/daftar-kegiatan', 'Admin\KegiatanController');

    Route::get('/opd-manajemen/delete/{opd_manajemen}', 'Admin\OpdController@destroy')->name('opd-manajemen.delete');
    Route::resource('/opd-manajemen', 'Admin\OpdController');
});

Route::group(['prefix' => 'opd', 'middleware' => ['auth', 'opd']], function () {
    Route::get('/', 'Opd\OpdController@index')->name('opd');
    Route::get('/profile/{id}', 'Opd\OpdController@profile')->name('opd.profile');
    Route::get('/profile/update/{id}/edit', 'Opd\OpdController@editProfile')->name('opd.edit-profile');
    Route::match(['put','patch'],'/profile/update/{id}', 'Opd\OpdController@updateProfile')->name('opd.update-profile');

    Route::get('/kegiatan/delete/{kegiatan}', 'Opd\KegiatanController@destroy')->name('kegiatan.delete');
    Route::get('/kegiatan/show-by-date/', 'Opd\KegiatanController@showByDate')->name('kegiatan.show-by-date');
    Route::resource('/kegiatan', 'Opd\KegiatanController');
});

resources/views/layout/includes/foot.blade.php
<!-- jQuery 3 -->
<script src="{{asset('js/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('js/bootstrap.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('js/adminlte.min.js')}}"></script>
<!-- DataTables -->
<script src="{{ asset('/plugin/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('/plugin/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{ asset('/plugin/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}"></script>
<script src="{{ asset('/plugin/select2/js/select2.min.js')}}"></script>

<script>
    $(document).ready(function () {
        $('#table_id').DataTable({
            responsive: true
        });

        $('#datepicker').datepicker({
            autoclose: true,
            format: 'dd/mm/yyyy'
        });

        $('.select2').select2({
              width: 'resolve'
        });
    });
</script>

<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>

resources/views/layout/includes/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>RAPI</b>
    </div>
    <strong>&copy Humas Protokol Provinsi Nusa Tenggara Barat </strong>
  </footer>

resources/views/layout/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>RAPI | @yield('title')</title>
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<link rel="stylesheet" href="{{asset('/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('/plugin/Ionicons/css/ionicons.min.css')}}">
<link rel="stylesheet" href="{{asset('/plugin/font-awesome/css/font-awesome.min.css')}}">
<link rel="stylesheet" href="{{asset('/css/AdminLTE.min.css')}}">
<link rel="stylesheet" href="{{asset('/plugin/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('/plugin/bootstrap-datepicker/css/bootstrap-datepicker.min.css')}}">
<link rel="stylesheet" href="{{asset('/plugin/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('/css/AdminLTE.min.css')}}">
<link rel="stylesheet" href="{{asset('/css/skins/_all-skins.min.css')}}">
<link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/layout/includes/header.blade.php
<header class="main-header">

    <!-- Logo -->
    <a href="{{ route('admin')}}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>RAPI</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>RAPI</b></span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">


                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{asset('/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{Auth::user()->nama}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{asset('/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
                            <p>
                                Alexander Pierce - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('user.logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

    </nav>
</header>

resources/views/layout/includes/notofication.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-info alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-info"></i> Info</h4>
        {{ $message }}
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i> Error!</h4>
        {{ $message }}
    </div>
@endif

resources/views/layout/includes/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">Menu Utama</li>
            @if(Auth::user()->role == 'admin')
                <li class="{{ (strpos(Route::currentRouteName(), 'opd-manajemen') === 0) ? 'active' : '' }}"><a
                            href="{{ route('opd-manajemen.index')}}"><i class="fa fa-dot-circle-o"></i> <span>Management
                        OPD</span></a></li>
                <li class="{{ (strpos(Route::currentRouteName(), 'user-manajemen') === 0) ? 'active' : '' }}"><a
                            href="{{ route('user-manajemen.index')}}"><i class="fa fa-dot-circle-o"></i> <span>Management
                        User</span></a></li>
                <li class="{{ (strpos(Route::currentRouteName(), 'daftar-kegiatan') === 0) ? 'active' : '' }}"><a
                            href="{{ route('daftar-kegiatan.index')}}"><i class="fa fa-dot-circle-o"></i> <span>Data
                        Kegiatan</span></a></li>
            @else
                <li class="@yield('profil-active')"><a
                            href="{{ route('opd.profile', Auth::user()->opd->id)}}"><i class="fa fa-dot-circle-o"></i> <span>Profil OPD</span></a>
                </li>
                <li class="{{ (strpos(Route::currentRouteName(), 'kegiatan') === 0) ? 'active' : '' }}"><a
                            href="{{ route('kegiatan.index')}}"><i class="fa fa-dot-circle-o"></i> <span>Kegiatan</span></a>
                </li>
            @endif
        </ul>
    </section>
</aside>